sat_server: 'satellite.bk.lab'
sat_user: admin
sat_password: 'R3dH4tBr4d!'
capsule_server: "{{ sat_server }}"
capsule_port: '9090'
policy_name: 'all'
policy_scan: "{{ policy_name }}"
crontab_hour: 2
crontab_minute: 0
crontab_weekdays: 0
