---
- name: check or apply the RHEL 7 STIG
  hosts: all
  roles:
    - role: mindpointgroup.stig_rhel6
      when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version | version_compare ('6', '=')
      
    - role: RedHatOfficial.rhel7_stig
      when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version | version_compare ('7', '=')

    - role: RedHatOfficial.rhel8_stig
      when:
      - ansible_os_family == "RedHat"
      - ansible_distribution_major_version | version_compare ('8', '=')