---
- name: run a SCAP scan
  hosts: all

  roles:
   - ansible-role-scap-client

  tasks:
  - name: "Run SCAP Scan"
    shell: "/usr/bin/foreman_scap_client {{ item.id }}"
    loop: "{{ policy }}"
    when: policy_scan == 'all' or item.name in policy_scan

