---
- name: run a SCAP scan
  hosts: all

  roles:
   - theforeman.foreman_scap_client

  tasks:
  - name: "Run SCAP Scan"
    shell: "/usr/bin/foreman_scap_client {{ foreman_scap_client_policies }}"

